### ISSUE TITLE
在src\app\input.cpp第三十一行

### ISSUE THREAD

**Issue by eli3374** [VisualGMQ/grogue#10]
在src\app\input.cpp第三十一行为什么要用static_cast

**Comment by VisualGMQ** [comment]
应该不用转换的，可能写顺手了。

顺便提醒一下这个工程后面可能要大改，不是很建议再看现在的代码了。你可以看看[这个](https://github.com/VisualGMQ/NickelEngine)，后面要把底层换成这个。输入部分的话应该是直接从这个仓库挪过去的。
